export const copy = {
  brand: "Nooré Dhaka",
  tagline: "বাংলাদেশি নারীদের জন্য লাক্সারি ফ্যাশন",
  nav: {
    collections: "কালেকশন",
    search: "খুঁজুন",
    about: "আমাদের গল্প",
    contact: "যোগাযোগ",
    cart: "কার্ট",
    account: "অ্যাকাউন্ট",
    login: "লগইন",
    logout: "লগআউট",
    admin: "অ্যাডমিন",
  },
  actions: {
    shopNow: "এখনই কিনুন",
    addToCart: "কার্টে যোগ করুন",
    addedToCart: "কার্টে যোগ হয়েছে",
    viewCart: "কার্ট দেখুন",
    checkout: "চেকআউট",
    placeOrder: "অর্ডার করুন",
    continueShopping: "আরও দেখুন",
    sendWhatsApp: "WhatsApp-এ পাঠান",
    save: "সংরক্ষণ করুন",
    delete: "মুছুন",
    edit: "এডিট",
    create: "নতুন যোগ করুন",
  },
  cart: {
    title: "আপনার কার্ট",
    empty: "কার্টে এখন কিছু নেই।",
    summary: "অর্ডার সারাংশ",
    subtotal: "সাবটোটাল",
    shipping: "ডেলিভারি",
    total: "মোট",
    freeShipping: "৳ ৭,০০০+ অর্ডারে ঢাকায় ফ্রি ডেলিভারি",
  },
  checkout: {
    title: "অর্ডার সম্পন্ন করুন",
    successTitle: "অর্ডার গ্রহণ করা হয়েছে",
    successBody:
      "আপনার অর্ডার সফলভাবে রেকর্ড হয়েছে। আমাদের টিম শীঘ্রই WhatsApp বা ফোনে কনফার্মেশন পাঠাবে।",
  },
  search: {
    title: "প্রোডাক্ট খুঁজুন",
    placeholder: "নাম, ক্যাটাগরি বা ফ্যাব্রিক লিখুন...",
    noResults: "কোনো প্রোডাক্ট পাওয়া যায়নি।",
    filters: "ফিল্টার",
    allCategories: "সব ক্যাটাগরি",
    sortFeatured: "ফিচার্ড",
    sortPriceLow: "দাম: কম থেকে বেশি",
    sortPriceHigh: "দাম: বেশি থেকে কম",
  },
  account: {
    loginTitle: "আপনার অ্যাকাউন্টে লগইন করুন",
    registerTitle: "নতুন অ্যাকাউন্ট তৈরি করুন",
    dashboardTitle: "আমার অ্যাকাউন্ট",
    ordersTitle: "আমার অর্ডার",
    noOrders: "এখনো কোনো অর্ডার নেই।",
  },
  admin: {
    title: "স্টোর অ্যাডমিন",
    products: "প্রোডাক্ট",
    orders: "অর্ডার",
    loginTitle: "অ্যাডমিন লগইন",
  },
  form: {
    name: "পূর্ণ নাম",
    phone: "ফোন নম্বর",
    email: "ইমেইল (ঐচ্ছিক)",
    address: "ডেলিভারি ঠিকানা",
    district: "জেলা",
    note: "নোট (ঐচ্ছিক)",
    password: "পাসওয়ার্ড",
    payment: "পেমেন্ট পদ্ধতি",
    cod: "ক্যাশ অন ডেলিভারি",
    bkash: "bKash",
    nagad: "Nagad",
  },
} as const;
