export type KajmamaLang = "bn" | "en";

export const COPY = {
  bn: {
    brand: "KajMama BD",
    tagline: "জেলা ও কাজ অনুযায়ী মিস্ত্রি খুঁজুন",
    heroTitle: "বিশ্বস্ত মিস্ত্রি খুঁজুন, কাজ হোক নিরাপদে",
    heroLead: "আপনার প্রয়োজনীয় কাজের জন্য খুঁজে নিন দক্ষ ও অভিজ্ঞ মিস্ত্রি।",
    searchCategory: "কাজের ধরন নির্বাচন করুন",
    findWorker: "কর্মী খুঁজুন",
    becomeWorker: "কর্মী হিসেবে যোগ দিন",
    postJob: "কাজ দিন",
    workers: "সকল কর্মী",
    jobs: "কাজ",
    login: "লগইন",
    register: "রেজিস্টার করুন",
    dashboard: "ড্যাশবোর্ড",
    logout: "লগআউট",
    how: "কিভাবে কাজ করবেন",
    trust: "বিশ্বস্ত মিস্ত্রি, নিরাপদ কাজ",
    footer: "KajMama BD — দক্ষ মিস্ত্রির সাথে কাজদাতাকে যুক্ত করে। আপনার কাজ, আপনার মানুষ।",
    home: "হোম",
    types: "কাজের ধরন",
    contact: "যোগাযোগ",
    blog: "ব্লগ",
    seeMore: "আরও দেখুন",
    seeAll: "সব দেখুন",
    applyFilter: "ফিল্টার প্রয়োগ করুন",
    resetFilter: "ফিল্টার রিসেট করুন",
    call: "কল করুন",
    needWorkers: "কর্মী লাগবে",
    allWorkers: "সকল কর্মী",
    admin: "অ্যাডমিন",
  },
  en: {
    brand: "KajMama BD",
    tagline: "Find workers by district and job type",
    heroTitle: "Find trusted tradespeople. Work, safely.",
    heroLead: "Skilled, experienced workers for the job you need — across Bangladesh.",
    searchCategory: "Select job type",
    findWorker: "Find a worker",
    becomeWorker: "Join as a worker",
    postJob: "Post a job",
    workers: "All workers",
    jobs: "Jobs",
    login: "Log in",
    register: "Register",
    dashboard: "Dashboard",
    logout: "Log out",
    how: "How it works",
    trust: "Trusted workers, safe work",
    footer: "KajMama BD — connecting skilled workers with people who need them.",
    home: "Home",
    types: "Job types",
    contact: "Contact",
    blog: "Blog",
    seeMore: "See more",
    seeAll: "See all",
    applyFilter: "Apply filters",
    resetFilter: "Reset filters",
    call: "Call",
    needWorkers: "Need workers",
    allWorkers: "All workers",
    admin: "Admin",
  },
} as const;
