import bcrypt from "bcryptjs";
import {
  CATEGORIES,
  COMMISSION_PCT,
  DEFAULT_ADMIN_BANKS,
  DEFAULT_ADMIN_MOBILES,
  DEFAULT_ADS,
  DEFAULT_OWNER_PIN,
  DEFAULT_PACKAGES,
  DEMO_PASSWORD,
} from "./constants";
import { newId } from "./http";
import { siteFeeOf } from "./premium";
import type { Booking, Job, KajmamaStore, Message, Review, User } from "./types";

function user(partial: Omit<User, "passwordHash" | "blocked" | "upazila" | "packageId" | "packageExpiresAt" | "payout"> & Partial<Pick<User, "upazila" | "packageId" | "packageExpiresAt" | "payout">>): User {
  return {
    passwordHash: "",
    blocked: false,
    ...partial,
    createdAt: partial.createdAt || new Date().toISOString(),
    upazila: partial.upazila || partial.area,
    packageId: partial.packageId || "basic",
    packageExpiresAt: partial.packageExpiresAt ?? null,
    payout: partial.payout || {
      bankName: "Dutch-Bangla Bank",
      bankAccount: `101${partial.phone.slice(-6)}`,
      bankHolder: partial.name,
      mobileBanking: partial.phone,
      mobileBankingType: "bkash",
    },
  };
}

export function createSeedStore(): KajmamaStore {
  const hash = bcrypt.hashSync(DEMO_PASSWORD, 10);
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;

  const workers: User[] = [
    user({
      id: "u_karim",
      name: "করিম মিয়া",
      phone: "01711111111",
      role: "worker",
      district: "ঢাকা",
      area: "মিরপুর",
      bio: "১২ বছরের ইলেকট্রিক ওয়্যারিং। ফ্ল্যাট, দোকান, বোর্ড — নিরাপদ কাজ।",
      skills: ["electrician"],
      experienceYears: 12,
      hourlyRate: 450,
      jobRate: 800,
      verified: true,
      available: true,
      createdAt: new Date(now - 40 * day).toISOString(),
    }),
    user({
      id: "u_salma",
      name: "সালমা বেগম",
      phone: "01711111112",
      role: "worker",
      district: "ঢাকা",
      area: "ধানমন্ডি",
      bio: "বাড়ি ও অফিস ডীপ ক্লিনিং। সময়মতো, পরিষ্কার সরঞ্জাম নিয়ে আসি।",
      skills: ["cleaning"],
      experienceYears: 6,
      hourlyRate: 300,
      jobRate: 1500,
      verified: true,
      available: true,
      createdAt: new Date(now - 28 * day).toISOString(),
    }),
    user({
      id: "u_rafiq",
      name: "রফিক প্লাম্বার",
      phone: "01711111113",
      role: "worker",
      district: "ঢাকা",
      area: "উত্তরা",
      bio: "লিক, কমোড, গিজার, হিidden পাইপ — জরুরি কলেও যাই।",
      skills: ["plumber"],
      experienceYears: 9,
      hourlyRate: 400,
      jobRate: 700,
      verified: true,
      available: true,
      createdAt: new Date(now - 22 * day).toISOString(),
    }),
    user({
      id: "u_nayeem",
      name: "নাঈম আহমেদ",
      phone: "01711111114",
      role: "worker",
      district: "চট্টগ্রাম",
      area: "আগ্রাবাদ",
      bio: "এসি সার্ভিসিং, গ্যাস, শিফট। ওয়ারেন্টিসহ কাজ।",
      skills: ["ac"],
      experienceYears: 7,
      hourlyRate: 500,
      jobRate: 1200,
      verified: true,
      available: true,
      createdAt: new Date(now - 18 * day).toISOString(),
    }),
    user({
      id: "u_farzana",
      name: "ফারজানা আক্তার",
      phone: "01711111115",
      role: "worker",
      district: "ঢাকা",
      area: "মোহাম্মদপুর",
      bio: "স্কুল-কলেজ গণিত ও ইংরেজি। ধৈর্য ধরে পড়াই।",
      skills: ["tutor"],
      experienceYears: 5,
      hourlyRate: 350,
      jobRate: 4000,
      verified: false,
      available: true,
      createdAt: new Date(now - 10 * day).toISOString(),
    }),
    user({
      id: "u_jalal",
      name: "জালাল উদ্দিন",
      phone: "01711111116",
      role: "worker",
      district: "গাজীপুর",
      area: "টঙ্গী",
      bio: "রং, পুটি, ডেম্প ওয়াল। ফ্ল্যাট হ্যান্ডওভারের কাজ করি।",
      skills: ["painter"],
      experienceYears: 11,
      hourlyRate: 380,
      jobRate: 2500,
      verified: true,
      available: true,
      createdAt: new Date(now - 15 * day).toISOString(),
    }),
    user({
      id: "u_shakil",
      name: "শাকিল ড্রাইভার",
      phone: "01711111117",
      role: "worker",
      district: "ঢাকা",
      area: "বনানী",
      bio: "পারিবারিক ও অফিস ড্রাইভিং। নিজের লাইসেন্স ও পরিষ্কার রেকর্ড।",
      skills: ["driver"],
      experienceYears: 8,
      hourlyRate: 250,
      jobRate: 1800,
      verified: true,
      available: true,
      createdAt: new Date(now - 12 * day).toISOString(),
    }),
    user({
      id: "u_mina",
      name: "মিনা খাতুন",
      phone: "01711111118",
      role: "worker",
      district: "সিলেট",
      area: "জিন্দাবাজার",
      bio: "ঘরোয়া রান্না ও পার্টি মেনু। হাইজিন খেয়াল রাখি।",
      skills: ["cook"],
      experienceYears: 10,
      hourlyRate: 280,
      jobRate: 2000,
      verified: true,
      available: true,
      createdAt: new Date(now - 8 * day).toISOString(),
    }),
    user({
      id: "u_imran",
      name: "ইমরান ইলেকট্রিক",
      phone: "01711111119",
      role: "worker",
      district: "ঢাকা",
      area: "বনানী",
      bio: "নতুন ফ্ল্যাট ওয়্যারিং, মিটার, জেনারেটর কানেকশন।",
      skills: ["electrician"],
      experienceYears: 8,
      hourlyRate: 420,
      jobRate: 900,
      verified: true,
      available: true,
      createdAt: new Date(now - 14 * day).toISOString(),
    }),
    user({
      id: "u_jasim",
      name: "জসিম পাইপ",
      phone: "01711111120",
      role: "worker",
      district: "গাজীপুর",
      area: "টঙ্গী",
      bio: "বাথরুম রিনোভেশন ও হিidden লিক খুঁজে বের করি।",
      skills: ["plumber"],
      experienceYears: 6,
      hourlyRate: 350,
      jobRate: 650,
      verified: true,
      available: true,
      createdAt: new Date(now - 9 * day).toISOString(),
    }),
    user({
      id: "u_rakib",
      name: "রাকিব কাঠমিস্ত্রি",
      phone: "01711111121",
      role: "worker",
      district: "ঢাকা",
      area: "মোহাম্মদপুর",
      bio: "কিচেন ক্যাবিনেট, দরজা, স্লাইডিং। মাপ নিয়ে কাজ।",
      skills: ["carpenter"],
      experienceYears: 14,
      hourlyRate: 400,
      jobRate: 2200,
      verified: true,
      available: true,
      createdAt: new Date(now - 11 * day).toISOString(),
    }),
    user({
      id: "u_sohel",
      name: "সোহেল রাজমিস্ত্রি",
      phone: "01711111122",
      role: "worker",
      district: "নারায়ণগঞ্জ",
      area: "ফতুল্লা",
      bio: "টাইলস, প্লাস্টার, ছোট মেরামত। সময়মতো শেষ করি।",
      skills: ["mason"],
      experienceYears: 13,
      hourlyRate: 360,
      jobRate: 1800,
      verified: true,
      available: true,
      createdAt: new Date(now - 7 * day).toISOString(),
    }),
    user({
      id: "u_babu",
      name: "বাবু মেকানিক",
      phone: "01711111123",
      role: "worker",
      district: "ঢাকা",
      area: "তেজগাঁও",
      bio: "গাড়ি সার্ভিসিং, ব্রেক, ইলেকট্রিক্যাল ফল্ট।",
      skills: ["mechanic"],
      experienceYears: 9,
      hourlyRate: 450,
      jobRate: 1500,
      verified: true,
      available: true,
      createdAt: new Date(now - 4 * day).toISOString(),
    }),
    user({
      id: "u_lina",
      name: "লীনা সেলাই",
      phone: "01711111124",
      role: "worker",
      district: "ঢাকা",
      area: "মিরপুর",
      bio: "কামিজ-সালোয়ার ফিটিং, অল্টার, ঘরে এসে মাপ।",
      skills: ["sewing"],
      experienceYears: 7,
      hourlyRate: 250,
      jobRate: 800,
      verified: false,
      available: true,
      createdAt: new Date(now - 3 * day).toISOString(),
    }),
  ].map((u) => {
    const premium = u.verified;
    return {
      ...u,
      passwordHash: hash,
      packageId: premium ? "yearly" : "basic",
      packageExpiresAt: premium ? new Date(now + 200 * day).toISOString() : null,
    };
  });

  const hirers: User[] = [
    user({
      id: "u_hirer_demo",
      name: "তানিয়া রহমান",
      phone: "01722222222",
      role: "hirer",
      district: "ঢাকা",
      area: "গুলশান",
      bio: "",
      skills: [],
      experienceYears: 0,
      hourlyRate: 0,
      jobRate: 0,
      verified: true,
      available: true,
      createdAt: new Date(now - 20 * day).toISOString(),
    }),
    user({
      id: "u_hirer_2",
      name: "আরিফ চৌধুরী",
      phone: "01722222223",
      role: "hirer",
      district: "ঢাকা",
      area: "মিরপুর",
      bio: "",
      skills: [],
      experienceYears: 0,
      hourlyRate: 0,
      jobRate: 0,
      verified: false,
      available: true,
      createdAt: new Date(now - 6 * day).toISOString(),
    }),
  ].map((u) => ({ ...u, passwordHash: hash }));

  const jobs: Job[] = [
    {
      id: "job_open_1",
      hirerId: "u_hirer_demo",
      categoryId: "electrician",
      title: "রুম ফ্যান ও দুইটা লাইট ঠিক",
      description: "মাস্টার বেডরুমের ফ্যান কাঁপে, বারান্দার দুইটা লাইট জ্বলে না। আজ সন্ধ্যার মধ্যে হলে ভালো।",
      district: "ঢাকা",
      upazila: "গুলশান",
      area: "গুলশান",
      budget: 1200,
      whenText: "আজ সন্ধ্যা",
      status: "open",
      createdAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "job_open_2",
      hirerId: "u_hirer_2",
      categoryId: "plumber",
      title: "কিচেনের সিঙ্ক লিক",
      description: "সিঙ্কের নিচে পানি পড়ছে। জরুরি।",
      district: "ঢাকা",
      upazila: "মিরপুর",
      area: "মিরপুর",
      budget: 800,
      whenText: "আজকের মধ্যে",
      status: "open",
      createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "job_done_1",
      hirerId: "u_hirer_demo",
      workerId: "u_salma",
      categoryId: "cleaning",
      title: "ফ্ল্যাট ডীপ ক্লিন",
      description: "৩ বেডের ফ্ল্যাট, কিচেন ও বাথরুমসহ।",
      district: "ঢাকা",
      upazila: "গুলশান",
      area: "গুলশান",
      budget: 3500,
      whenText: "গত শুক্রবার",
      status: "completed",
      createdAt: new Date(now - 6 * day).toISOString(),
    },
  ];

  const fee = siteFeeOf(3500, COMMISSION_PCT);
  const bookings: Booking[] = [
    {
      id: "bk_done_1",
      jobId: "job_done_1",
      hirerId: "u_hirer_demo",
      workerId: "u_salma",
      status: "paid",
      price: 3500,
      commissionPct: COMMISSION_PCT,
      siteFee: fee.siteFee,
      workerPayout: fee.workerPayout,
      paidAt: new Date(now - 5 * day).toISOString(),
      paymentMethod: "bkash",
      paymentRef: "DEMO-BKASH-3500",
      createdAt: new Date(now - 6 * day).toISOString(),
      updatedAt: new Date(now - 5 * day).toISOString(),
    },
  ];

  const messages: Message[] = [
    {
      id: newId("m"),
      bookingId: "bk_done_1",
      fromUserId: "u_hirer_demo",
      text: "শুক্রবার সকাল ১০টায় আসতে পারবেন?",
      createdAt: new Date(now - 6 * day).toISOString(),
    },
    {
      id: newId("m"),
      bookingId: "bk_done_1",
      fromUserId: "u_salma",
      text: "জি আপু, ১০টায় পৌঁছাব। ডিটারজেন্ট নিয়ে আসছি।",
      createdAt: new Date(now - 6 * day + 20 * 60 * 1000).toISOString(),
    },
  ];

  const reviews: Review[] = [
    {
      id: newId("rv"),
      bookingId: "bk_done_1",
      fromUserId: "u_hirer_demo",
      toUserId: "u_salma",
      rating: 5,
      text: "খুব পরিষ্কার কাজ, সময়মতো এসেছিল।",
      createdAt: new Date(now - 5 * day).toISOString(),
    },
    {
      id: newId("rv"),
      bookingId: "bk_done_1",
      fromUserId: "u_salma",
      toUserId: "u_hirer_demo",
      rating: 5,
      text: "ভালো মানুষ, পেমেন্ট ঠিকমতো দিয়েছেন।",
      createdAt: new Date(now - 5 * day).toISOString(),
    },
    ...[
      ["u_karim", 5, "ওয়্যারিং নিরাপদ, কাজ পরিষ্কার।"],
      ["u_karim", 5, "ফ্যান ও বোর্ড ঠিক করে দিয়েছেন।"],
      ["u_rafiq", 5, "লিক তাড়াতাড়ি ধরেছে।"],
      ["u_rafiq", 4, "ভালো প্লাম্বার, দাম যৌক্তিক।"],
      ["u_nayeem", 5, "এসি সার্ভিস দারুণ।"],
      ["u_jalal", 5, "রং সমান, সময়মতো শেষ।"],
      ["u_shakil", 5, "ড্রাইভিং নিরাপদ ও ভদ্র।"],
      ["u_mina", 5, "রান্না সুস্বাদু, হাইজিন ভালো।"],
      ["u_imran", 4, "ইলেকট্রিক কাজ ঠিকঠাক।"],
      ["u_jasim", 5, "বাথরুম রিনোভেশন ভালো হয়েছে।"],
      ["u_rakib", 5, "ক্যাবিনেট মাপমতো।"],
      ["u_sohel", 4, "টাইলস কাজ নিখুঁত।"],
      ["u_babu", 5, "গাড়ি সার্ভিস ভালো।"],
    ].map(([toUserId, rating, text], i) => ({
      id: `rv_seed_${i}`,
      bookingId: "bk_done_1",
      fromUserId: "u_hirer_demo",
      toUserId: String(toUserId),
      rating: Number(rating),
      text: String(text),
      createdAt: new Date(now - (4 - (i % 4)) * day).toISOString(),
    })),
  ];

  return {
    settings: {
      ownerPin: DEFAULT_OWNER_PIN,
      siteName: "KajMama BD",
      siteNameBn: "KajMama BD",
      taglineBn: "জেলা ও কাজ অনুযায়ী মিস্ত্রি খুঁজুন",
      taglineEn: "Find workers by district and job type",
      contactPhone: "01712-345678",
      contactEmail: "support@kajmamabd.com",
      contactWhatsapp: "01712345678",
      contactFacebook: "https://facebook.com/kajmamabd",
      commissionPct: COMMISSION_PCT,
      banks: DEFAULT_ADMIN_BANKS,
      mobiles: DEFAULT_ADMIN_MOBILES,
    },
    categories: CATEGORIES.map((c) => ({ ...c })),
    packages: DEFAULT_PACKAGES.map((p) => ({ ...p })),
    ads: DEFAULT_ADS.map((a) => ({ ...a })),
    users: [...workers, ...hirers],
    jobs,
    bookings,
    messages,
    reviews,
    support: [],
  };
}
