import bcrypt from "bcryptjs";
import { COMMISSION_PCT, DEFAULT_OWNER_PIN, DEMO_PASSWORD } from "./constants";
import { newId } from "./http";
import type { Booking, Job, KajmamaStore, Message, Review, User } from "./types";

function user(partial: Omit<User, "passwordHash" | "createdAt" | "blocked"> & { createdAt?: string }): User {
  return {
    blocked: false,
    createdAt: partial.createdAt || new Date().toISOString(),
    passwordHash: "",
    ...partial,
  };
}

export function createSeedStore(): KajmamaStore {
  const hash = bcrypt.hashSync(DEMO_PASSWORD, 10);
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;

  const workers: User[] = [
    user({
      id: "u_karim",
      name: "করিম মিয়া",
      phone: "01711111111",
      role: "worker",
      district: "ঢাকা",
      area: "মিরপুর",
      bio: "১২ বছরের ইলেকট্রিক ওয়্যারিং। ফ্ল্যাট, দোকান, বোর্ড — নিরাপদ কাজ।",
      skills: ["electrician"],
      experienceYears: 12,
      hourlyRate: 450,
      jobRate: 800,
      verified: true,
      available: true,
      createdAt: new Date(now - 40 * day).toISOString(),
    }),
    user({
      id: "u_salma",
      name: "সালমা বেগম",
      phone: "01711111112",
      role: "worker",
      district: "ঢাকা",
      area: "ধানমন্ডি",
      bio: "বাড়ি ও অফিস ডীপ ক্লিনিং। সময়মতো, পরিষ্কার সরঞ্জাম নিয়ে আসি।",
      skills: ["cleaning"],
      experienceYears: 6,
      hourlyRate: 300,
      jobRate: 1500,
      verified: true,
      available: true,
      createdAt: new Date(now - 28 * day).toISOString(),
    }),
    user({
      id: "u_rafiq",
      name: "রফিক প্লাম্বার",
      phone: "01711111113",
      role: "worker",
      district: "ঢাকা",
      area: "উত্তরা",
      bio: "লিক, কমোড, গিজার, হিidden পাইপ — জরুরি কলেও যাই।",
      skills: ["plumber"],
      experienceYears: 9,
      hourlyRate: 400,
      jobRate: 700,
      verified: true,
      available: true,
      createdAt: new Date(now - 22 * day).toISOString(),
    }),
    user({
      id: "u_nayeem",
      name: "নাঈম আহমেদ",
      phone: "01711111114",
      role: "worker",
      district: "চট্টগ্রাম",
      area: "আগ্রাবাদ",
      bio: "এসি সার্ভিসিং, গ্যাস, শিফট। ওয়ারেন্টিসহ কাজ।",
      skills: ["ac"],
      experienceYears: 7,
      hourlyRate: 500,
      jobRate: 1200,
      verified: true,
      available: true,
      createdAt: new Date(now - 18 * day).toISOString(),
    }),
    user({
      id: "u_farzana",
      name: "ফারজানা আক্তার",
      phone: "01711111115",
      role: "worker",
      district: "ঢাকা",
      area: "মোহাম্মদপুর",
      bio: "স্কুল-কলেজ গণিত ও ইংরেজি। ধৈর্য ধরে পড়াই।",
      skills: ["tutor"],
      experienceYears: 5,
      hourlyRate: 350,
      jobRate: 4000,
      verified: false,
      available: true,
      createdAt: new Date(now - 10 * day).toISOString(),
    }),
    user({
      id: "u_jalal",
      name: "জালাল উদ্দিন",
      phone: "01711111116",
      role: "worker",
      district: "গাজীপুর",
      area: "টঙ্গী",
      bio: "রং, পুটি, ডেম্প ওয়াল। ফ্ল্যাট হ্যান্ডওভারের কাজ করি।",
      skills: ["painter"],
      experienceYears: 11,
      hourlyRate: 380,
      jobRate: 2500,
      verified: true,
      available: true,
      createdAt: new Date(now - 15 * day).toISOString(),
    }),
    user({
      id: "u_shakil",
      name: "শাকিল ড্রাইভার",
      phone: "01711111117",
      role: "worker",
      district: "ঢাকা",
      area: "বনানী",
      bio: "পারিবারিক ও অফিস ড্রাইভিং। নিজের লাইসেন্স ও পরিষ্কার রেকর্ড।",
      skills: ["driver"],
      experienceYears: 8,
      hourlyRate: 250,
      jobRate: 1800,
      verified: true,
      available: true,
      createdAt: new Date(now - 12 * day).toISOString(),
    }),
    user({
      id: "u_mina",
      name: "মিনা খাতুন",
      phone: "01711111118",
      role: "worker",
      district: "সিলেট",
      area: "জিন্দাবাজার",
      bio: "ঘরোয়া রান্না ও পার্টি মেনু। হাইজিন খেয়াল রাখি।",
      skills: ["cook"],
      experienceYears: 10,
      hourlyRate: 280,
      jobRate: 2000,
      verified: true,
      available: true,
      createdAt: new Date(now - 8 * day).toISOString(),
    }),
  ].map((u) => ({ ...u, passwordHash: hash }));

  const hirers: User[] = [
    user({
      id: "u_hirer_demo",
      name: "তানিয়া রহমান",
      phone: "01722222222",
      role: "hirer",
      district: "ঢাকা",
      area: "গুলশান",
      bio: "",
      skills: [],
      experienceYears: 0,
      hourlyRate: 0,
      jobRate: 0,
      verified: true,
      available: true,
      createdAt: new Date(now - 20 * day).toISOString(),
    }),
    user({
      id: "u_hirer_2",
      name: "আরিফ চৌধুরী",
      phone: "01722222223",
      role: "hirer",
      district: "ঢাকা",
      area: "মিরপুর",
      bio: "",
      skills: [],
      experienceYears: 0,
      hourlyRate: 0,
      jobRate: 0,
      verified: false,
      available: true,
      createdAt: new Date(now - 6 * day).toISOString(),
    }),
  ].map((u) => ({ ...u, passwordHash: hash }));

  const jobs: Job[] = [
    {
      id: "job_open_1",
      hirerId: "u_hirer_demo",
      categoryId: "electrician",
      title: "রুম ফ্যান ও দুইটা লাইট ঠিক",
      description: "মাস্টার বেডরুমের ফ্যান কাঁপে, বারান্দার দুইটা লাইট জ্বলে না। আজ সন্ধ্যার মধ্যে হলে ভালো।",
      district: "ঢাকা",
      area: "গুলশান",
      budget: 1200,
      whenText: "আজ সন্ধ্যা",
      status: "open",
      createdAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "job_open_2",
      hirerId: "u_hirer_2",
      categoryId: "plumber",
      title: "কিচেনের সিঙ্ক লিক",
      description: "সিঙ্কের নিচে পানি পড়ছে। জরুরি।",
      district: "ঢাকা",
      area: "মিরপুর",
      budget: 800,
      whenText: "আজকের মধ্যে",
      status: "open",
      createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "job_done_1",
      hirerId: "u_hirer_demo",
      workerId: "u_salma",
      categoryId: "cleaning",
      title: "ফ্ল্যাট ডীপ ক্লিন",
      description: "৩ বেডের ফ্ল্যাট, কিচেন ও বাথরুমসহ।",
      district: "ঢাকা",
      area: "গুলশান",
      budget: 3500,
      whenText: "গত শুক্রবার",
      status: "completed",
      createdAt: new Date(now - 6 * day).toISOString(),
    },
  ];

  const bookings: Booking[] = [
    {
      id: "bk_done_1",
      jobId: "job_done_1",
      hirerId: "u_hirer_demo",
      workerId: "u_salma",
      status: "completed",
      price: 3500,
      commissionPct: COMMISSION_PCT,
      createdAt: new Date(now - 6 * day).toISOString(),
      updatedAt: new Date(now - 5 * day).toISOString(),
    },
  ];

  const messages: Message[] = [
    {
      id: newId("m"),
      bookingId: "bk_done_1",
      fromUserId: "u_hirer_demo",
      text: "শুক্রবার সকাল ১০টায় আসতে পারবেন?",
      createdAt: new Date(now - 6 * day).toISOString(),
    },
    {
      id: newId("m"),
      bookingId: "bk_done_1",
      fromUserId: "u_salma",
      text: "জি আপু, ১০টায় পৌঁছাব। ডিটারজেন্ট নিয়ে আসছি।",
      createdAt: new Date(now - 6 * day + 20 * 60 * 1000).toISOString(),
    },
  ];

  const reviews: Review[] = [
    {
      id: newId("rv"),
      bookingId: "bk_done_1",
      fromUserId: "u_hirer_demo",
      toUserId: "u_salma",
      rating: 5,
      text: "খুব পরিষ্কার কাজ, সময়মতো এসেছিল।",
      createdAt: new Date(now - 5 * day).toISOString(),
    },
    {
      id: newId("rv"),
      bookingId: "bk_done_1",
      fromUserId: "u_salma",
      toUserId: "u_hirer_demo",
      rating: 5,
      text: "ভালো মানুষ, পেমেন্ট ঠিকমতো দিয়েছেন।",
      createdAt: new Date(now - 5 * day).toISOString(),
    },
  ];

  return {
    settings: {
      ownerPin: DEFAULT_OWNER_PIN,
      siteName: "Kajmama",
      siteNameBn: "কাজমামা",
      taglineBn: "কাজ লাগলে মামা আছে।",
      taglineEn: "Work needed? Mama is here.",
      contactPhone: "01700000000",
      commissionPct: COMMISSION_PCT,
    },
    users: [...workers, ...hirers],
    jobs,
    bookings,
    messages,
    reviews,
  };
}
