import bcrypt from "bcryptjs";
import type { Product, StoreData } from "./types";
import { uid } from "./id";

function product(
  partial: Omit<Product, "id" | "createdAt" | "updatedAt" | "active" | "lowStockAt"> & {
    lowStockAt?: number;
  },
): Product {
  const now = new Date().toISOString();
  return {
    id: uid("prd"),
    active: true,
    lowStockAt: partial.lowStockAt ?? 5,
    createdAt: now,
    updatedAt: now,
    ...partial,
  };
}

export async function createSeedData(): Promise<StoreData> {
  const pinHash = await bcrypt.hash("1234", 10);
  const products: Product[] = [
    product({
      name: "Linen Casual Shirt",
      sku: "MEN-SH-001",
      barcode: "8901001001001",
      category: "men",
      brand: "Loom Basics",
      price: 1490,
      cost: 720,
      stock: 42,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Ivory", "Sky", "Olive"],
      imageHue: 160,
      description: "Breathable everyday linen shirt",
    }),
    product({
      name: "Slim Chino Pant",
      sku: "MEN-PT-014",
      barcode: "8901001001002",
      category: "men",
      brand: "Loom Basics",
      price: 1890,
      cost: 900,
      stock: 28,
      sizes: ["30", "32", "34", "36"],
      colors: ["Khaki", "Navy", "Black"],
      imageHue: 35,
    }),
    product({
      name: "Floral Summer Kurti",
      sku: "WMN-KR-022",
      barcode: "8901001001003",
      category: "women",
      brand: "Loom Studio",
      price: 1290,
      cost: 610,
      stock: 35,
      sizes: ["S", "M", "L"],
      colors: ["Coral", "Mint", "Lilac"],
      imageHue: 340,
    }),
    product({
      name: "Denim Jacket",
      sku: "WMN-JK-008",
      barcode: "8901001001004",
      category: "women",
      brand: "Loom Studio",
      price: 2590,
      cost: 1280,
      stock: 16,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Indigo", "Washed Blue"],
      imageHue: 220,
    }),
    product({
      name: "Kids Polo Tee",
      sku: "KID-TS-003",
      barcode: "8901001001005",
      category: "kids",
      brand: "Loom Mini",
      price: 690,
      cost: 280,
      stock: 50,
      sizes: ["4Y", "6Y", "8Y", "10Y"],
      colors: ["Red", "Yellow", "Teal"],
      imageHue: 12,
    }),
    product({
      name: "Cotton Saree Blouse",
      sku: "WMN-BL-011",
      barcode: "8901001001006",
      category: "women",
      brand: "Loom Studio",
      price: 890,
      cost: 350,
      stock: 8,
      lowStockAt: 10,
      sizes: ["32", "34", "36", "38"],
      colors: ["Maroon", "Gold", "White"],
      imageHue: 0,
    }),
    product({
      name: "Canvas Tote Bag",
      sku: "ACC-BG-001",
      barcode: "8901001001007",
      category: "accessories",
      brand: "Loom Goods",
      price: 490,
      cost: 160,
      stock: 60,
      sizes: ["One size"],
      colors: ["Natural", "Black"],
      imageHue: 45,
    }),
    product({
      name: "Leather Belt",
      sku: "ACC-BL-004",
      barcode: "8901001001008",
      category: "accessories",
      brand: "Loom Goods",
      price: 790,
      cost: 300,
      stock: 22,
      sizes: ["30", "32", "34", "36"],
      colors: ["Brown", "Black"],
      imageHue: 25,
    }),
    product({
      name: "Premium Rice 5kg",
      sku: "GRC-RC-5KG",
      barcode: "8901001001009",
      category: "grocery",
      brand: "Daily Shelf",
      price: 520,
      cost: 430,
      stock: 80,
      sizes: ["5kg"],
      colors: [],
      imageHue: 80,
    }),
    product({
      name: "Mustard Oil 1L",
      sku: "GRC-OIL-1L",
      barcode: "8901001001010",
      category: "grocery",
      brand: "Daily Shelf",
      price: 310,
      cost: 250,
      stock: 4,
      lowStockAt: 8,
      sizes: ["1L"],
      colors: [],
      imageHue: 50,
    }),
    product({
      name: "Oversized Hoodie",
      sku: "MEN-HD-006",
      barcode: "8901001001011",
      category: "men",
      brand: "Loom Basics",
      price: 2190,
      cost: 1050,
      stock: 19,
      sizes: ["M", "L", "XL", "XXL"],
      colors: ["Charcoal", "Forest", "Sand"],
      imageHue: 140,
    }),
    product({
      name: "Embroidered Panjabi",
      sku: "MEN-PJ-019",
      barcode: "8901001001012",
      category: "men",
      brand: "Loom Studio",
      price: 2490,
      cost: 1180,
      stock: 14,
      sizes: ["M", "L", "XL"],
      colors: ["White", "Cream", "Steel"],
      imageHue: 200,
    }),
  ];

  return {
    settings: {
      shopName: "LOOM",
      tagline: "Supershop & clothing till",
      address: "Mirpur, Dhaka",
      phone: "01700-000000",
      currency: "BDT",
      pinHash,
      taxRate: 0,
    },
    products,
    sales: [],
  };
}
